### ISSUE TITLE
Item Database Checklist

### ISSUE THREAD

**Issue by knyghtmare** [babaissarkar/WISh#3]
- [ ] Default Era

   - [ ] Rebels
   - [ ] Loyalists
   - [ ] Knalgan Alliance
   - [ ] Undead
   - [ ] Northerners
   - [ ] Drakes
   - [ ] Dunefolk

- [ ] War of Legends
   - [ ] Aragwaithi
   - [ ] Windsong
   - [ ] Drakes
   - [ ] Knalgan Alliance (has some extra units in SP)
   - [ ] Sylvans
   - [ ] Northerners (has some extra units)
   - [ ] Loyalists (has some extra units)
   - [ ] Deep Elves
   - [ ] Undead (has some extra units)
   - [ ] Dark Legion (can be shared with Loyalists)
   - [ ] Quenoth Elves (can be shared with Default::Rebels)
   - [ ] Steelhive
   - [ ] Minotaurs
   - [ ] Outlaws
   - [ ] Vampires
   - [ ] Dunefolk (same as Default one)

**Comment by babaissarkar** [comment]
* Rebels
   * Faerie Bow, Tier X (elves)
* Loyalists
   * Arzenth, Tier X (magi)
   * Storm Trident (copies), Tier UC (merfolk or spear-based unit)
   * Oceanos Trident (original of Storm Trident), Tier X (merfolk or spear based unit)
* Aragwaithi
   * Electrifyre, Tier X (sword-based units)
* Unassigned
   * Frost Sword, Tier X (sword-based units)
   * Lightspear, Tier X (spear-based units)
